# DO NOT EDIT THIS FILE

SUBMIT  := src/FileLineIterator.java src/TweetParser.java src/MarkovChain.java src/TwitterBot.java test/FileLineIteratorTest.java test/MarkovChainTest.java test/TweetParserTest.java test/TwitterBotTest.java

JAVAC	:= javac

DEPENDS := src/*.java

TESTS := \
	test/FileLineIteratorTest.java \
	test/MarkovChainTest.java \
	test/TweetParserTest.java \
	test/TwitterBotTest.java

HWNAME := hw08
ts := $(shell /bin/date "+%Y-%m-%d-%H:%M:%S")

ZIPNAME := $(HWNAME)-submit($(ts)).zip

.PHONY: all TwitterBot clean zip

all:	

bin:
	mkdir bin

TwitterBot : $(DEPENDS) bin
	$(JAVAC) -d bin $(DEPENDS)

bin/TwitterBot.class : $(DEPENDS) bin
	$(JAVAC) -d bin $(DEPENDS)

run : bin/TwitterBot.class
	java -cp "bin" TwitterBot

zip: $(SUBMIT)
	zip '$(ZIPNAME)' $(SUBMIT)

clean:
	rm -f src/*.class bin/* test/*.class bin/*
	rm -rf *.zip
